### ISSUE TITLE
'LabelTemplate' object has no attribute 'object_to_print'

### ISSUE THREAD

**Issue by jpeg2600** [yellowcrescent/inventree-zpl-plugin#2]
Hi! The plugin installs correctly but I'm getting the following error when I try to generate a label. 

I'm using InvenTree 0.16.8

I think it's the same issue as here: https://github.com/SergeoLacruz/inventree-zebra-plugin/issues/6 

Thanks

![image](https://github.com/user-attachments/assets/34b68c25-b765-422e-8851-c47bded3e017)

```
Traceback (most recent call last):

File "/home/inventree/src/backend/InvenTree/report/api.py", line 271, in print
plugin.print_labels(

File "/home/inventree/src/backend/InvenTree/plugin/base/label/mixins.py", line 180, in print_labels
self.print_label(**print_args)

File "/usr/local/lib/python3.11/site-packages/inventree_zpl/zpl_label.py", line 73, in print_label
object_to_print = kwargs['label_instance'].object_to_print
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'LabelTemplate' object has no attribute 'object_to_print'
```

**Comment by yellowcrescent** [comment]
Sorry, just saw your issue-- not sure if you've figured out a solution already.

The version I originally wrote this plugin against was v0.12. Let me test it out against the latest version and see if I can get it fixed.

**Comment by jpeg2600** [comment]
Hey no worry, I figured out how to make the Zebra plugin work so it's all good for now @yellowcrescent
